apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "genai.labels" . | nindent 4 }}
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      name: http
