ingress-nginx:
  controller:
    replicaCount: 2
    resources:
      requests: { cpu: "100m", memory: "128Mi" }
      limits:   { cpu: "500m", memory: "512Mi" }
    config:
      proxy-read-timeout: "300"
      proxy-body-size: "50m"
      use-forwarded-headers: "true"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 6
