apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: genai-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ramamishra7262/AI-Platform-AKS.git
    targetRevision: main
    path: helm/genai-platform
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: genai
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
