apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: genai-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.keyvault.clientId | quote }}
    keyvaultName: {{ .Values.keyvault.name | quote }}
    tenantId: {{ .Values.keyvault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: openai-api-key
          objectType: secret
        - |
          objectName: search-api-key
          objectType: secret
  secretObjects:
    - secretName: genai-secrets
      type: Opaque
      data:
        - objectName: openai-api-key
          key: AZURE_OPENAI_API_KEY
        - objectName: search-api-key
          key: AZURE_SEARCH_API_KEY
