apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: genai
  annotations:
    azure.workload.identity/client-id: "<BACKEND_CLIENT_ID>"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-sa
  namespace: genai
  annotations:
    azure.workload.identity/client-id: "<RAG_CLIENT_ID>"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingestion-sa
  namespace: genai
  annotations:
    azure.workload.identity/client-id: "<INGESTION_CLIENT_ID>"
  labels:
    azure.workload.identity/use: "true"
