apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base/genai.yaml]
patches:
  - target: { kind: Application, name: genai-platform }
    patch: |
      - op: replace
        path: /spec/source/targetRevision
        value: develop
